statics: "/" # 静态文件根目录，可用于 CDN 加速
assets: "/source/_data/assets" # 图片资源存放目录
css: "css" # css 存放目录 (不建议改动)
js: "js" # js 存放目录 (不建议改动)

menu:
  home: / || home
  submenu:
    default: /source/_post/测试文章.md || user
    link: /source/_post/测试文章.md || cloud
  link2: /source/_post/测试文章.md/ || coffee


widgets:
  random_posts: true # 随机文章
  recent_comments: true # 显示最近评论


# 页尾全站统计
footer:
  since: 2024 # 开始时间
  count: true # 开启
# 文章界面统计
post:
  count: true # 开启


alternate: "Aston" #站点大标题，（比 title 高一级，但仅在 index 显示）

social:
  github: https://github.com/Aston17sq || github || "#191717"


homeConfig:
  gradient: false # 使用CSS渐变作为文章封面
  # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)
